contact/urls.py
from django.urls import path
from .views import *

app_name = 'contact'
urlpatterns = [
    path('', index, name='contact'),
    path('thankyou/', thank_you, name='thank_you_page')
]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('contact/', include('contact.urls')),
    path('services/', include('services.urls'))
]

home/urls.py
from django.urls import path
from .views import *

app_name = 'home'
urlpatterns = [
    path("", index, name='home')
]

services/urls.py
from django.urls import path
from .views import *

app_name = 'service'
urlpatterns = [
    path('service/', index, name='services')
]

contact/models.py
from django.db import models


class CustomerContact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=100)
    message = models.TextField()

home/models.py
from django.db import models

# Create your models here.

services/models.py
from django.db import models


class Services(models.Model):
    service_name = models.CharField(max_length=100)
    service_details = models.TextField()

contact/views.py
from django.shortcuts import render
from .models import CustomerContact


def index(request):
    return render(request, 'contact/index.html')


def thank_you(request):
    if request.POST:
        customer = CustomerContact()
        data = request.POST.dict()
        name = data.get('customer_name')
        email = data.get('email')
        subject = data.get('subject')
        message = data.get('message')
        customer.name = name
        customer.email = email
        customer.subject = subject
        customer.message = message
        customer.save()
    return render(request, 'contact/thank_you.html')

home/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'home/index.html')

services/views.py
from django.core.paginator import Paginator
from django.shortcuts import render
from services.models import Services

# TODO  ad

def index(request):
    services = Services.objects.all()
    return render(request, 'services/index.html', {'services': services})

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Website</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'home:home' %}">MHS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home:home' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'service:services' %}">Services</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'contact:contact' %}" >Contact</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
{% block content %}

{% endblock %}
<!-- Remove the container if you want to extend the Footer to full width. -->
  <footer class="sticky-bottom text-center text-lg-start text-dark" style="background-color: #ECEFF1">
    <section class="d-flex justify-content-between p-4 text-white" style="background-color: #21D192">
    </section>
    <section class="">
      <div class="container text-center text-md-start mt-5">
        <div class="row mt-3">
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            <h6 class="text-uppercase fw-bold">Useful links</h6>
            <hr
                class="mb-4 mt-0 d-inline-block mx-auto"
                style="width: 60px; background-color: #7c4dff; height: 2px"
                />
            <p>
              <a href="#!" class="text-dark">Your Account</a>
            </p>
            <p>
              <a href="#!" class="text-dark">Become an Affiliate</a>
            </p>
            <p>
              <a href="#!" class="text-dark">Shipping Rates</a>
            </p>
            <p>
              <a href="#!" class="text-dark">Help</a>
            </p>
          </div>
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <h6 class="text-uppercase fw-bold">Contact</h6>
            <hr
                class="mb-4 mt-0 d-inline-block mx-auto"
                style="width: 60px; background-color: #7c4dff; height: 2px"
                />
            <p><i class="fas fa-home mr-3"></i> Cleveland, TN 37312, US</p>
            <p><i class="fas fa-envelope mr-3"></i> domerackimark@gmail.com</p>
            <p><i class="fas fa-phone mr-3"></i>423-490-5701</p>
          </div>
        </div>
      </div>
    </section>
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
      © 2020 Copyright:
      <a class="text-dark" href="https://mdbootstrap.com/"
         >mdhandyman.com</a
        >
    </div>
  </footer>
</body>
</html>

templates/contact/index.html
{% extends 'base.html' %}

{% block content %}


<section class="m-5">
    <h2 class="h1-responsive font-weight-bold text-center my-4">Contact us</h2>
    <p class="text-center w-responsive mx-auto mb-5">Do you have any questions? Please do not hesitate to contact us directly. Our team will come back to you within
        a matter of hours to help you.</p>
    <div class="row p-5">
        <div class="col-md-9 mb-md-0 mb-5">
            <form action="{% url 'contact:thank_you_page' %}"  method="post">
                {% csrf_token %}
                <!--Grid row-->
                <div class="row">
                    <!--Grid column-->
                    <div class="col-md-6">
                        <div class="md-form mb-0">
                            <input type="text" id="customer_name" name="customer_name" class="form-control">
                            <label for="customer_name" class="">Your name</label>
                        </div>
                    </div>
                    <!--Grid column-->

                    <!--Grid column-->
                    <div class="col-md-6">
                        <div class="md-form mb-0">
                            <input type="text" id="email" name="email" class="form-control">
                            <label for="email" class="">Your email</label>
                        </div>
                    </div>
                    <!--Grid column-->

                </div>
                <!--Grid row-->

                <!--Grid row-->
                <div class="row">
                    <div class="col-md-12">
                        <div class="md-form mb-0">
                            <input type="text" id="subject" name="subject" class="form-control">
                            <label for="subject" class="">Subject</label>
                        </div>
                    </div>
                </div>
                <!--Grid row-->

                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-12">

                        <div class="md-form">
                            <textarea type="text" id="message" name="message" rows="2" class="form-control md-textarea"></textarea>
                            <label for="message">Your message</label>
                        </div>

                    </div>
                </div>
                <!--Grid row-->
                <input class="btn btn-primary" type="submit" value="Send">
            </form>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-3 text-center">
            <ul class="list-unstyled mb-0">
                <li><i class="fas fa-map-marker-alt fa-2x"></i>
                    <p>Cleveland, TN 37312, USA</p>
                </li>

                <li><i class="fas fa-phone mt-4 fa-2x"></i>
                    <p>423-590-5701</p>
                </li>

                <li><i class="fas fa-envelope mt-4 fa-2x"></i>
                    <p>domerackimark@gmail.com</p>
                </li>
            </ul>
        </div>

    </div>

</section>
{% endblock %}

templates/contact/thank_you.html
{% extends 'base.html' %}
    {% block content %}
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static '/css/contact_css/site.css' %}">
        <div class="container">
        <h4 class="text-center">Thank you for reaching out! We look forward to speaking with you!</h4>
            <img class="background_image" src="{% static 'imgs/tool-2820950_1280.jpeg'%}" alt="background image">
        </div>
    {% endblock %}

templates/home/index.html
{% extends 'base.html' %}
{% block content %}
<!-- Gallery -->
    <h3 class="text-center pt-4">Past Work</h3>
<div class="row p-3">
    <div class="col-lg-4 col-md-12 mb-4 mb-lg-0">
        <img
          src="https://mdbcdn.b-cdn.net/img/Photos/Horizontal/Nature/4-col/img%20(73).webp"
          class="w-100 shadow-1-strong rounded mb-4"
          alt="Boat on Calm Water"
        />
        <img
          src="https://mdbcdn.b-cdn.net/img/Photos/Vertical/mountain1.webp"
          class="w-100 shadow-1-strong rounded mb-4"
          alt="Wintry Mountain Landscape"
        />
    </div>
  <div class="col-lg-4 mb-4 mb-lg-0">
    <img
      src="https://mdbcdn.b-cdn.net/img/Photos/Vertical/mountain2.webp"
      class="w-100 shadow-1-strong rounded mb-4"
      alt="Mountains in the Clouds"
    />

    <img
      src="https://mdbcdn.b-cdn.net/img/Photos/Horizontal/Nature/4-col/img%20(73).webp"
      class="w-100 shadow-1-strong rounded mb-4"
      alt="Boat on Calm Water"
    />
  </div>

  <div class="col-lg-4 mb-4 mb-lg-0">
    <img
      src="https://mdbcdn.b-cdn.net/img/Photos/Horizontal/Nature/4-col/img%20(18).webp"
      class="w-100 shadow-1-strong rounded mb-4"
      alt="Waves at Sea"
    />

    <img
      src="https://mdbcdn.b-cdn.net/img/Photos/Vertical/mountain3.webp"
      class="w-100 shadow-1-strong rounded mb-4"
      alt="Yosemite National Park"
    />
  </div>
</div>
{% endblock %}

templates/services/index.html
{% extends 'base.html' %}
{# Services template#}
{% block content %}
<div class="row p-5">
{% for service in services %}
 <div class="col-lg-4 col-md-12 d-flex justify-content-around mt-5">
   <div class="card w-75">
      <div class="card-body">
        <h5 class="card-title">{{ service.service_name }}</h5>
        <p class="card-text">{{ service.service_details }}</p>
        <a href="{% url 'contact:contact' %}" class="btn btn-info">Get A Quote</a>
      </div>
   </div>
 </div>
{% endfor %}
 </div>
{%  endblock %}